# Generated by Django 5.1.4 on 2024-12-18 08:02

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Alphafold3",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("result_path", models.TextField()),
                ("create_date", models.DateTimeField()),
            ],
        ),
    ]
